/**
 * Architecture data loader — public renderer.
 *
 * Imports the canonical JSON (mirrored from
 * ~/Desktop/HOME/Claude_Home/architecture-data.json) and exposes a sanitized
 * public view: nodes flagged `visibility: "internal-only"` are stripped, and
 * `publicLabel` / `publicDescription` replace the internal copy.
 *
 * Single source of truth: Claude_Home/architecture-data.json. To update the
 * public site, copy the updated JSON into src/data/architecture.json and
 * commit. The internal HTML in Artifacts/ reads the same source via
 * Artifacts/architecture-data.js (regenerated by build-architecture-data.sh).
 */
import raw from "./architecture.json";

export type NodeStatus = "live" | "deferred";
export type Visibility = "both" | "internal-only";

export type ArchChild = {
  id: string;
  label: string;
  publicLabel: string;
  status: NodeStatus;
  visibility: Visibility;
  description: string;
  publicDescription: string;
};

export type ArchNode = {
  id: string;
  tier: number;
  column: number;
  label: string;
  publicLabel: string;
  status: NodeStatus;
  visibility: Visibility;
  description: string;
  publicDescription: string;
  badges?: string[];
  children?: ArchChild[];
};

export type ArchRule = { html: string; publicHtml: string };

export type ArchData = {
  lastUpdated: string;
  phasesShipped: string;
  phasesPending: string;
  tiers: { n: number; name: string; publicName: string }[];
  columns: { n: number; label: string; publicLabel: string }[];
  nodes: ArchNode[];
  loadingArrows: { from: string; to: string; type: "auto" | "trigger" }[];
  rules: { autoLoad: ArchRule[]; onTrigger: ArchRule[] };
};

const data = raw as unknown as ArchData;

export type PublicNode = {
  id: string;
  tier: number;
  column: number;
  label: string;
  description: string;
  status: NodeStatus;
  badges: string[];
  children: { id: string; label: string; description: string; status: NodeStatus }[];
};

/** Sanitized view: only nodes visible publicly, with public copy substituted. */
export function getPublicArchitecture() {
  const nodes: PublicNode[] = data.nodes
    .filter((n) => n.visibility === "both")
    .map((n) => ({
      id: n.id,
      tier: n.tier,
      column: n.column,
      label: n.publicLabel,
      description: n.publicDescription,
      status: n.status,
      badges: n.badges ?? [],
      children: (n.children ?? [])
        .filter((c) => c.visibility === "both")
        .map((c) => ({
          id: c.id,
          label: c.publicLabel,
          description: c.publicDescription,
          status: c.status,
        })),
    }));

  return {
    lastUpdated: data.lastUpdated,
    phasesShipped: data.phasesShipped,
    phasesPending: data.phasesPending,
    tiers: data.tiers.map((t) => ({ n: t.n, name: t.publicName })),
    columns: data.columns.map((c) => ({ n: c.n, label: c.publicLabel })),
    nodes,
    loadingArrows: data.loadingArrows,
    rules: {
      autoLoad: data.rules.autoLoad.map((r) => r.publicHtml),
      onTrigger: data.rules.onTrigger.map((r) => r.publicHtml),
    },
  };
}
